apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: rajneeshmahala/flaskfrntnd:v1
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "demouser"
        - name: DB_PASSWORD
          value: "demopassword"
        - name: DB_NAME
          value: "demodb"
        ports:
        - containerPort: 5000  # Flask default port
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
