apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
  labels:
    name: nginxwebserver
spec:
  containers:
  - name: "webserver"
    image: "nginx:latest"
    
    ports:
      - containerPort: 8080
